# Generated by Django 2.1.7 on 2019-06-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('staff_detail_list', '可以查看 员工个人信息的数据'),), 'verbose_name_plural': '用户表'},
        ),
    ]
