# Generated by Django 2.1.7 on 2019-06-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190612_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('staff_detail_list', '可以查看 员工个人信息的数据'), ('fina_state_list', '可以访问kingadmin表里每条数据的修改页')), 'verbose_name_plural': '用户表'},
        ),
    ]
