# Generated by Django 2.1.7 on 2019-06-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190612_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('app_staff_detail', '可以查看 员工个人信息的数据'), ('app_fina_state', '可以访问kingadmin表里每条数据的修改页')), 'verbose_name_plural': '用户表'},
        ),
    ]
