# Generated by Django 2.1.7 on 2019-06-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190612_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('app_staff_detail', '可以查看员工个人信息的数据'), ('app_fina_state', '可以查看财务报表'), ('app_payroll', '可以查看工资条')), 'verbose_name_plural': '用户表'},
        ),
    ]
